trellis/mail.md

Mandrill's free tier changed a while ago and you removed it from your docs. This just removes a small reference to it in the mail docs.

Trellis: Remove minor reference to Mandrill

---

trellis/deploys.md
trellis/local-development-setup.md
trellis/mail.md
trellis/passwords.md
trellis/remote-server-setup.md
trellis/security.md
trellis/vault.md

roots/trellis#317
The new `vault.md` docs page might fit well after `passwords.md` in the page order. I'm guessing you'll first add the new page via the WordPress admin and then sync with this docs repo. I'll then rebase if necessary.

Trellis: Add docs for Ansible Vault

---

trellis/multisite.md

Because of the switch to oscarotero/env

Use `env` instead of `getenv`

---

sage/theme-templates.md

I haven't found any precedence for "intact" being properly written otherwise. Some reference:
http://grammarist.com/spelling/intact/
http://public.wsu.edu/~brians/errors/intact.html

Change "in tact" to "intact"

---

sage/theme-wrapper.md

This PR adds a second backslash to match the other functions you'd find inside extras.php
There was previously one used in this file however it is not displaying [in the docs](https://roots.io/sage/docs/theme-wrapper/) and so copy pasting results in errors.
E.g. this original code:
```php
<?php
add_filter('sage/wrap_base', __NAMESPACE__ . '\sage_wrap_base_cpts'); // Add our function to the sage/wrap_base filter
function sage_wrap_base_cpts($templates) {
$cpt = get_post_type(); // Get the current post type
if ($cpt) {
array_unshift($templates, 'base-' . $cpt . '.php'); // Shift the template to the front of the array
}
return $templates; // Return our modified array with base-$cpt.php at the front of the queue
}
?>
```
is displayed on the site as:
(with no backslashes)

Update theme-wrapper base-*.php filter call

---

trellis/deploys.md
trellis/wordpress-sites.md

roots/trellis#622
The new code block in the description of `site_hosts` breaks up the bullet points a little bit. Let me know if you would prefer a new separate `site_hosts` section instead.

Reformat site_hosts to use canonical and redirects

---

trellis/passwords.md
trellis/security.md

[roots/trellis#614](https://github.com/roots/trellis/pull/614)

Trellis: Switch to automated handling of user passwords

---

trellis/ssl.md

Note about including 'www' subdomain in "redirects" since https://github.com/roots/trellis/pull/622
Removed section about `www_redirect` because it seems irrelevant in light of #622, but I don't know for sure.

Notes about Trellis 0.9.8 changes to redirects

---

trellis/local-development-setup.md

I've run into the issue of attempting to run concurrent boxes with Trellis installations based off the initial docs. This change will account for the option to change the IP address in the Vagrantfile to allow for concurrent runs when needed and addresses it from initial setup.

Account for Vagrantfile IP configuration

---

trellis/multisite.md

This PR fixes a small typo in the multisite section of Trellis' docs.

Fix typo in trellis/multisite.md.

---

trellis/multisite.md

As per discussion [here](https://discourse.roots.io/t/multisite-subdomain-instructions-out-of-date/8362).

Update subdomain config for current Vagrantfile

---

trellis/ssl.md

Better documentation for HSTS `preload` and `max-age`.
Ref: https://github.com/roots/trellis/pull/728

Trellis SSL + HSTS updates

---

sage/theme-development-and-building.md

- Remove file extension from slick js import. (File extension causes the build to throw `5:8  error  Unexpected use of file extension "js" for "slick-carousel/slick/slick.min.js"  import/extensions`
)
- Update external js dependencies example to reflect the current file structure.
- Update scss dependencies to reflect the current file structure

Update theme-development-and-building.md doc

---

trellis/debugging-php.md
trellis/mail.md

Use two words for "set up" as a verb
-extremely using
+extremely useful
Apparently there were missing trailing newlines (at the end of the documents) so my editor automatically added them when it saved.

trellis: Fix minor typos

---

sage/theme-development-and-building.md

Added 4th step how to configure font paths for 3rd party packages. Example uses the Slick Slider. In short you must configure path before importing the package. And remember to use "~" to tell Webpack to locate these files from node_modules folder:
`$slick-font-path: "~slick-carousel/slick/fonts/" !default;`
In Slick Slider you have to configure path for the ajax-loader.gif:
`$slick-loader-path: "~slick-carousel/slick/" !default;`

Sage 9 - 3rd party package's relative paths in production

---

trellis/security.md
trellis/ssh-keys.md
trellis/troubleshooting.md

Transfers "Troubleshooting" text from roots/trellis#744's README to the Trellis troubleshooting docs.

Trellis: Add SSH connections section to troubleshooting docs

---

trellis/deploys.md

If I understand things correctly, the point of SSH forwarding is that the server does **not** need its own SSH key. I suppose that word was simply missing. :)

Add missing word

---

trellis/multisite.md

The example code for application.php has 'subdomain install: true' but the wordpress_sites.yml example code has subdomains: false
I think we should pick one.

Consistency required

---

trellis/multisite.md

The comment next to `define('SUBDOMAIN_INSTALL', false);` in the Multisite docs says that the define should be set to `true` for subdirectories. This should read "subdomains", and this PR fixes that.

Fix SUBDOMAIN_INSTALL code comment

---

trellis/multisite.md

As discussed with @fullyint in [this Discourse thread](https://discourse.roots.io/t/multisite-on-remote-server-redirect-loop-database-error/10421/4), here are the instructions for Multisite
- to install Wordpress on staging and production with WP-CLI;
- to fix `/wp/` in Multisite URLs;
- to generate Let's Encrypt SSL certificates for subdomains.

Multisite: install; fix /wp/ in URLs; LE SSL certs for subdomains

---

trellis/remote-server-setup.md

roots/trellis#895 bumped Ansible version requirement to 2.4

Trellis: Require Ansible 2.4

---

trellis/local-development-setup.md

I saw that the config for the Vagrant has been refactored to the vagrant.default.yml file. Updating the docs to reflect this change.

Refer to the new vagrant config yml file

---

trellis/installing-trellis.md

I found a broken link ('Requirements') in the [Installing Trellis](https://roots.io/trellis/docs/installing-trellis/) doc. It was pointing to `https://roots.io/trellis/docs/installing-trellis/#https://roots.io/trellis/docs/remote-server-setup/`, but should be pointing to https://roots.io/trellis/docs/remote-server-setup/#requirements.

Fix broken link to Remote Server Requirements (Installing Trellis)

---

trellis/ssl.md

Noticed this while going through the docs.

Add missing markdown link for HSTS recommendations

---

trellis/nginx-includes.md

Note for https://github.com/roots/trellis/pull/966 
Sidenote: 
Thoughts on putting a suggestion to setup a project-template in the docs and/or Trellis readme? It would make the all folder more understandable for it's purpose.
Examples:
- https://github.com/partounian/trellis
- https://github.com/TangRufus/trellis/tree/project-template
Also I can improve the instructions here on repo setup, trellis best practices  and add it somewhere if you like. I have had great success setting up multiple repos with one upstream each, in fact it's very straightforward and more understandable then the whole subtree idea.
@TangRufus @swalkinshaw @retlehs 
Sorry if I missed an @ for someone

Make a note about "all" folder in includes.d

---

sage/theme-localization.md

Fixed typo (space after `findutils`)

Fixed typo (space after findutils)

---

trellis/passwords.md

Git Encrypt is deprecated and no longer maintained, so it makes sense to switch to the tool its former maintainer recommends switching to.

Change suggestion for git encryption tool

---

sage/theme-deployment.md

Deployment guide based on my issues discussed at https://discourse.roots.io/t/sage-soberwp-controller-app-title-in-blade-view-is-not-working/10326/21

deploy via FTP guide added

---

getting-started/macos-development-environment-sage.md

Options are no longer a thing for Homebrew formulae. This does the same thing though.

Update macOS yarn installation command

---

trellis/wordpress-sites.md

Hopefully I am not missing anything - it looks like the default is actually true:
Matches https://github.com/roots/trellis/blob/2e5bc068b3607cf3dc95f5b1f075ee6201d2a990/roles/wordpress-setup/defaults/main.yml#L45

Trellis docs - update h5bp extra security default

---

trellis/ssh-keys.md

Added a warning note. When re-provisioning a server with a users tag trellis provision --tags users env it does not remove the keys from authorized_keys. (https://github.com/roots/trellis/issues/1087)

Added warning for removing keys

---

getting-started/windows-development-environment-trellis.md

The previous instructions incorrectly recommended aliasing `vagrant.exe` to `vagrant`, which is not recommended. This adjusts the instructions and adds a bit more explanation.

Revise and correct instructions for Vagrant on WSL

---

trellis/ssl.md

Not sure the exact language desired, but figured it would be good to have a link to https://discourse.roots.io/t/trellis-and-lets-encrypt-v1-end-of-life/ in the docs :)

Add note regarding Lets Encrypt v1 EOL

---

getting-started/windows-basic-setup.md

There was a post on discourse recently about missing php-zip at Windows Setup Guide: https://discourse.roots.io/t/getting-started-document-php-zip/17116/2
I went through my notes and found I had the same issue as well (I am WSL user). I also fixed it by running "sudo apt-get install php-zip".

add sudo apt install php-zip

---

getting-started/windows-basic-setup.md

In case `ppa:ondrej/php` _alias_ `php-zip` to `php7.4-zip` when PHP 7.4 is released.

Specific `php-zip` PHP version number

---

docs/trellis/master/ssh-keys.md

There isn't much information online on how to use Trellis for AWS hosting so I would find it useful to add it to the documentation.

adds SSH key information for AWS users

---

docs/trellis/master/user-contributed-extensions.md

I've taken over the jillro/trellis-backup-role repo and brought is back to life. Also took the opportunity to add my NIXStats role in here :)
The 2 backup roles are quite similar, but (Xilonz/trellis-backup-role )[https://github.com/Xilonz/trellis-backup-role] is a bit more configurable and soon™ will have some nice QoL updates.

Add Xilonz's extensions to Trellis user-contributed-extensions.md

---

docs/bedrock/master/server-configuration.md
docs/sage/9.x/installation.md

The examples use `~-` which is not supported by nginx. It should be `~*`.
http://nginx.org/en/docs/http/ngx_http_core_module.html#location
Looks like these code examples were changed during the conversion to VuePress.

Fix nginx location modifiers

---

docs/trellis/master/existing-projects.md

The documentation wrongly states that when importing the `uploads` directory from an existing WordPress project to Trellis, the copy should be placed in the `site/app` directory, which is not a standard Treillis/Bedrock path.
This pull request changes the path to the proper `site/web/app` location.

Fix path to uploads import directory

---

docs/trellis/master/fastcgi-caching.md

Trellis code has..:
```yml
nginx_skip_cache_uri: /wp-admin/|/wp-json/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml
```
... since https://github.com/roots/trellis/commit/3cf196a3ee6044f8b8af9f6de567a817f1322cc7 but the docs don't reflect the addition of `wp-json`.

Add wp-json to skip_cache_uri
