trellis/security.md

See https://github.com/roots/trellis/pull/344

Trellis: Update docs for sshd_permit_root_login

---

trellis/deploys.md
trellis/remote-server-setup.md
trellis/security.md

Trellis: Revise how ansible-playbook cmd specifies env

---

trellis/local-development-setup.md

Trellis: Add docs for www-redirect option

---

trellis/deploys.md
trellis/remote-server-setup.md

Updates for https://github.com/roots/trellis/pull/451

Rename subtree_path to repo_subtree_path

---

trellis/local-development-setup.md

Add Trellis config initial_permalink_structure

---

trellis/deploys.md
trellis/local-development-setup.md

This change was made in roots/trellis@ac38982, but isn't reflected in the docs.

Change system_cron -> env.disable_wp_cron

---

trellis/installing-trellis.md
trellis/windows.md

Add information on using vagrant-winnfsd on Windows with VirtualBox to improve performance.
https://github.com/roots/trellis/pull/527

Add information on improving Windows Virtualbox performance

---

sage/theme-configuration-and-setup.md
sage/theme-development-and-building.md
sage/theme-installation.md

Mostly clarifications with slight re-arrangements and addition of Theme Structure (pulled from README).

Sage 9 Docs revisions

---

sage/theme-wrapper.md

fixed typo

---

trellis/installing-trellis.md

Bump Vagrant version in docs

---

trellis/wordpress-sites.md

Document `current_path` option see https://github.com/roots/trellis/pull/607

Document current_path option

---

trellis/installing-trellis.md
trellis/remote-server-setup.md

Doc changes for https://github.com/roots/trellis/pull/626

Update Ubuntu references to 16.04

---

sage/theme-development-and-building.md

As per the sage repo [https://github.com/roots/sage](https://github.com/roots/sage)

Update npm run watch to npm start

---

trellis/deploys.md
trellis/windows.md

Appends `bin/`to references to our shell scripts, pending roots/trellis#680

Update *.sh locations in preparation for https://github.com/roots/trellis/pull/680

---

trellis/ssl.md
trellis/troubleshooting.md

Trellis: Add Let's Encrypt troubleshooting info

---

trellis/troubleshooting.md

Trellis: Add troubleshooting tips for known_hosts

---

trellis/installing-trellis.md

Trellis: Require Ansible 2.2

---

trellis/deploys.md

Trellis deploy docs: Mention new finalize-before.yml

---

trellis/nginx-includes.md

Add additional nginx sites templates section

---

trellis/deploys.md

Trellis: Accommodate deploy hook vars formatted as lists

---

sage/theme-development-and-building.md

Other build tools mention their histories then this should be in there for consistency.

Add front-end package manager history

---

trellis/user-contributed-extensions.md

Reference : https://github.com/roots/trellis/pull/650#issuecomment-307654840

Add user contributed backup role to docs

---

trellis/deploys.md

Added Instructions to rollback to a specific release (found in the rollback role source code)

Instructions to rollback to a specific release

---

sage/theme-configuration-and-setup.md

Changed Theme Structure chart from 8.5.1 to 9-beta3
Fixes #101

updated theme structure chart

---

trellis/installing-trellis.md
trellis/remote-server-setup.md
trellis/windows.md

Docs for https://github.com/roots/trellis/pull/824

ansible_local docs

---

sage/theme-development-and-building.md

Fixes https://github.com/roots/docs/issues/115

Add image in CSS example

---

sage/theme-development-and-building.md

Update  theme-development-and-build.md

---

trellis/debugging-php.md

Look ma, Microsoft made a decent text editor! 🤓

Added link to Visual Studio Code plugin

---

trellis/user-contributed-extensions.md

Add [trellis-backup-during-deploy](https://github.com/ItinerisLtd/trellis-backup-during-deploy)

User Contributed Extensions: Add trellis-backup-during-deploy

---

getting-started/macos-basic-setup.md
getting-started/macos-development-environment-sage.md
getting-started/macos-development-environment-trellis.md

Migrate actual documentation into files

---

bedrock/configuration-files.md
bedrock/folder-structure.md

With some reference to the old way and discussion. As per session with @austinpray.

Document the new approach to WP Configuration

---

getting-started/ubuntu-linux-development-environment-trellis.md

Even the official pip documentation does not capitalize it.

Fix name, pip should be lowercase

---

sage/theme-development-and-building.md

If merged, this PR would close issue #52. 
This will alert users reading the docs to the benign nature of the error, and will hopefully reduce user confusion. It will also provide us with something to link to when the question comes up.

Add note re: 404 on CSS during `yarn watch`

---

trellis/multisite.md

Update multisite docs to reflect new bedrock config api

---

sage/theme-development-and-building.md

Document the change from https://github.com/roots/sage/pull/2080, which dispatches events when each JS route runs.

Document JS route events

---

trellis/wordpress-sites.md

This is not documented, I had to dig into the source code to find how to enable/disable some config files.
Might help other users ;)

Add HTML5 Boilerplate server config doc

---

bedrock/installing-bedrock.md

Simple PR to bump step 2 of the installation method to include the new DSN variable as well as make it uniform with Bedrock's README.

Update Step 2 of Installation

---

trellis/deploys.md

Reference deploy_keep_releases in deploys.md

---

sage/sage-compatibility.md
sage/theme-development-and-building.md

This adds notes about this issue, as suggested here: https://github.com/roots/sage/issues/2147#issuecomment-457341438

Add warning about IE compat w/ CustomEvent

---

sage/theme-installation.md

ref https://github.com/roots/trellis/pull/1075

Add instructions for denying access to Blade files

---

getting-started/windows-development-environment-trellis.md

After checking that the recommended process worked, I realized I should update this with a few clarifications and troubleshooting tips I discovered during my tests.

Additional clarifications and troubleshooting tips

---

getting-started/windows-development-environment-trellis.md

`export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"` twice

Remove identical command

---

sage/theme-installation.md

ref: https://github.com/roots/trellis/pull/1116/files
Need help on `.htaccess`

Block dependency manager files by Nginx

---

getting-started/macos-basic-setup.md

https://github.com/roots/docs/issues/201#issuecomment-555548921

Remove cask install from macOS basic setup

---

trellis/ssl.md

Related to comment by @swalkinshaw  on https://github.com/roots/trellis/issues/1117#issuecomment-561235678

Include note about vagrant-trellis-cert

---

docs/.vuepress/config.js

Fixes the broken editLink at the bottom of each page.

fix docsBranch

---

docs/bedrock/master/configuration.md

Fix broken link from Bedrock docs to Trellis docs.

Fix broken link

---

docs/trellis/master/ssh-keys.md

Update Trellis' SSH keys

---

docs/trellis/master.js
docs/trellis/master/sage-integration.md

Add Sage Integration page to Trellis

---

docs/bedrock/master/local-development.md

DDEV is actively developed and is continuing to amaze me. Please add it to the list!

Add DDEV as a viable option for local development

---

docs/trellis/master/deployments.md

Fix typo in Trellis deploy hooks

---

docs/getting-started/macos.md

homebrew install script has updated here
Bash installer by itchyny · Pull Request #256 · Homebrew/install https://github.com/Homebrew/install/pull/256

updated homebrew install script

---

docs/trellis/master/ssl.md

Provisioning fails without it!

Add letsencrypt_contact_emails instructions
